### ISSUE TITLE
Background Texture Not Persisting When Scrolling

### ISSUE THREAD

**Issue by shouryamanekar** [r2hu1/Culina-Share#1]
# Background Texture Not Persisting When Scrolling

## Description
When scrolling the page, the background texture is not persisting and seems to be disappearing or not rendering correctly.

## Steps to Reproduce
1. Open the website/page.
2. Scroll down/up.
3. Observe that the background texture is not consistently visible.

## Expected Behavior
The background texture should remain visible and consistent even when scrolling.

## Actual Behavior
The background texture is not present when scrolling, which deviates from the expected behavior.

## Screenshots

https://github.com/r2hu1/Culina-Share/assets/72398499/c83ebd72-408e-4028-b48f-21f3b28cbc98

## Environment
- Operating System: Windows
- Browser: Chrome

## Labels
- bug
- frontend (if applicable)

**Comment by r2hu1** [comment]
haha its Intentionally not an bug, if you want to make the texures go to `/app/layout.js` and go to <div className="..... change the position absolute to fixed that's it!
