### ISSUE TITLE
Issue: Recipe Not Added When Contributed

### ISSUE THREAD

**Issue by shouryamanekar** [r2hu1/Culina-Share#2]
# Issue: Recipe Not Added When Contributed

## Description
Contributors are facing an issue where the submitted recipe is not successfully added to the system.

## Steps to Reproduce
1. Navigate to the contribute page.
2. Fill out the required information for a new recipe.
3. Submit the form to contribute the recipe.
4. Observe whether the recipe is successfully added or not.

## Expected Behavior
Upon contributing a recipe, it should be added to the system and reflected in the recipe database.

## Actual Behavior
Recipes submitted through the contribute form are not being added to the system as expected.

## Screenshots
![image](https://github.com/r2hu1/Culina-Share/assets/72398499/2c6e911e-3d35-4068-901e-fc68fe6929d3)

![image](https://github.com/r2hu1/Culina-Share/assets/72398499/5929cc36-938f-4bd8-8c56-4c0e285900a8)

![image](https://github.com/r2hu1/Culina-Share/assets/72398499/1a4fdf8d-d852-4302-9a77-077d3a86325a)

## Environment
- Operating System: Windows
- Browser: Chrome

## Labels
- bug
- backend

**Comment by shouryamanekar** [comment]
## Additional Comment

### Description
I also tried contributing a recipe by providing a YouTube link instead of an image link, and the issue persists. The recipe is still not being added to the system.

### Steps to Reproduce
1. Navigate to the contribute page.
2. Fill out the required information for a new recipe.
3. Instead of providing an image link, submit the form with a YouTube link.
4. Observe whether the recipe is successfully added or not.

### Expected Behavior
Contributing a recipe with a YouTube link should be a valid scenario, and the recipe should be added to the system.

### Actual Behavior
Even when providing a YouTube link instead of an image link, the recipe is not being added as expected.

### Screenshots
![image](https://github.com/r2hu1/Culina-Share/assets/72398499/b6845b03-f429-48a5-8514-fc9ca65235cb)

![image](https://github.com/r2hu1/Culina-Share/assets/72398499/99df5850-3084-4cd4-b38c-3481dccee805)

![image](https://github.com/r2hu1/Culina-Share/assets/72398499/50e28ae8-a59b-4c65-8c6c-ef5cc481165f)


### Environment
- Operating System: Windows
- Browser: Chrome

**Comment by r2hu1** [comment]
> shouryamanekar

i disabled it because some of the group members spammed 100's of unnecessary recipes , go to the `app/(details)/new/page.jsx` and uncommit the code and then go to the server_actions folder and add new file named getDbRecipe.js and simply copy the existing configs and paste there, thats it

**Comment by r2hu1** [comment]
closing this issue
